title: "Anh Le Blog"
logo: "/assets/img/anhle-logo-cropped.png"
masthead_title: " "
name: "Anh Le"
description: "System Engineer | Cloud | Kubernetes | Ceph"
url: "https://anhlx2502.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes"

minimal_mistakes_skin: "dark"

plugins:
  - jekyll-include-cache
  - jekyll-paginate

paginate: 3
paginate_path: /page:num/

search: true
powered_by: false

markdown: kramdown
highlighter: rouge

author:
  name: "Anh Le"
  avatar: "/assets/img/anhle.jpg"
  bio: "System Engineer | Cloud Infrastructure"
  location: "Vietnam"
  email: "anhle267@gmail.com"

  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/anhlx2502"

    - label: "YouTube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/@anhlx2502"

include:
  - _pages

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      related: true